# solver_options:
#     regularization: 1e-6
#     back_end: qpoases
#     control_dt: 0.001
# stack:
#     -   - EE_1
#         - EE_2
stack:
    - [EE]
    - [joint_imp]
# constraints:
#     ["JointLimits", "VelocityLimits"]
# EE_1:
#     type: Interaction
#     base_link: L_0_A
#     distal_link: ee_A
# EE_2:
#     type: Interaction
#     base_link: L_0_B
#     distal_link: ee_B
EE:
    type: Interaction
    base_link: base_link
    distal_link: ee_E
    impedance_ref_link: ee_E
    force_max:
        - 100000.0
        - 100000.0
        - 100000.0
        - 10000.0
        - 10000.0
        - 10000.0
    stiffness:
        - 10000.0
        - 10000.0
        - 10000.0
        - 2000.0
        - 2000.0
        - 20.0
    # stiffness:
    #     - 10000.0
    #     - 10000.0
    #     - 10000.0
    #     - 1000.0
    #     - 1000.0
    #     - 2.0 # 10.0
    # stiffness:
    #     - 5000.0
    #     - 5000.0
    #     - 5000.0
    #     - 500.0
    #     - 500.0
    #     - 500.0
    damping:
        - 0.7
        - 0.7
        - 0.7
        - 0.7
        - 0.7
        - 0.7
    
    
    indices: [0, 1, 2, 3, 4]

joint_imp:
    type: JointImpedance
    lib_name: libCartesianInterfaceSolverAlberoImpedance.so
    stiffness: 20.0  # 20.0 - 0.0
    damping: 80.0    # 80.0
    # disabled_joints: [J7_E]
    chain: chain_E