context:
  session: concert
  params:
    hw_type: ec_imp
    roslaunch: roslaunch


ecat:
  machine: embedded@10.24.10.100
  docker: noble-ros2-xeno-dev-1
  cmd: ecat_master
  session: control
  force_sigquit: true


xbot2:
  machine: embedded@10.24.10.100
  docker: noble-ros2-xeno-dev-1
  cmd: xbot2-core --hw {hw_type} -V
  ready_check: timeout 3 ros2 topic echo --once /xbotcore/statistics
  session: control
  variants:
    HW Type:
      - Impedance:
          params:
            hw_type: ec_imp
      - Idle:
          params:
            hw_type: ec_idle
      - Position:
          params:
            hw_type: ec_pos
      - Base Only:
          params:
            hw_type: ec_hybrid


# wait_ecat_online:
#   machine: embedded@10.24.10.100
#   cmd: ecat_wait_master_online
#   persistent: false
#   show_ui: false

# matlogger:
#   machine: embedded@10.24.10.100
#   cmd: rosrun xbot_ros robot_state_logger


# robot_design_studio:
#   machine: embedded@10.24.10.100
#   cmd: robot-design-studio


# linfa:
#   machine: concert@10.24.10.101
#   cmd: docker start -i linfa
#   show_ui: false
  

# drill_camera:
#   machine: concert@10.24.10.101
#   cmd: "{roslaunch} concert_perception rs_d435.launch enable_camera_front:=false enable_camera_back:=false enable_camera_drill:=true camera3:=drill_camera_E"
#   # cmd: "{roslaunch} concert_perception rs_d435.launch enable_camera_front:=false enable_camera_back:=false enable_camera_drill:=true"
#   ready_check: timeout 3 rostopic echo -n 1 /drill_camera_E/aligned_depth_to_color/image_raw
#   # ready_check: timeout 3 rostopic echo -n 1 /drill_camera_E/aligned_depth_to_color/image_raw
#   session: perception
#   show_ui: false


# front_camera:
#   machine: concert@10.24.10.102
#   cmd: "{roslaunch} concert_perception rs_d435.launch enable_camera_front:=true enable_camera_back:=false enable_camera_drill:=false"
#   ready_check: timeout 3 rostopic echo -n 1 /D435i_camera_front/aligned_depth_to_color/image_raw
#   session: perception
#   show_ui: false


front_lidar:
  machine: concert@10.24.10.101
  docker: noble-ros2-dev-1
  cmd: ros2 launch concert_config velodyne-VLP16_front.launch.py
  ready_check: timeout 3 ros2 topic echo --once /VLP16_lidar_front/velodyne_points
  session: perception
  show_ui: false


back_lidar:
  machine: concert@10.24.10.102
  docker: noble-ros2-dev-1
  cmd: ros2 launch concert_config velodyne-VLP16_back.launch.py
  ready_check: timeout 3 ros2 topic echo --once /VLP16_lidar_back/velodyne_points
  session: perception
  show_ui: false


# ultrasound:
#   machine: concert@10.24.10.102
#   cmd: "{roslaunch} concert_perception bosch_uss5.launch"
#   ready_check: timeout 3 rostopic echo -n 1 /bosch_uss5/ultrasound_fl_lat
#   session: perception
#   show_ui: false


# odometry:
#   machine: concert@10.24.10.101
#   cmd: "{roslaunch} concert_odometry concert_odometry.launch"
#   ready_check: timeout 3 rostopic echo -n 1 /concert_odometry/base_link/odom


# bringup_control:
#   machine: concert@10.24.10.102
#   cmd: "{roslaunch} concert_autonomous_drilling bringup.launch planner:=false"
#   session: control
#   depends:
#     - perception


# bringup_vision:
#   machine: concert@10.24.10.101
#   cmd: "{roslaunch} concert_autonomous_drilling bringup_vision.launch"
#   session: control
#   depends:
#     - perception


# # sanding:
# #   cmd: rosrun wall_following wall_following_node _tree_name:=sanding
# #   depends:
# #     - ultrasound
# #     - odometry
# #     - front_lidar


# sanding:
#   cmd: rosrun wall_following wall_following_node _tree_name:=sanding
#   depends:
#     - ultrasound
#     - odometry
#     - front_lidar



# coworker_supervisor:
#   cmd: rosrun coworker_supervisor actions_manager_node
#   depends:
#     - xbot2

# drill_pattern:
#   cmd: rosrun wall_following wall_following_node _tree_name:=drill_pattern

# ## meta-commands

# perception:
#   cmd: echo run perception
#   persistent: false
#   depends:
#     - drill_camera
#       #- front_camera
#     - front_lidar
#     - back_lidar
#     - ultrasound
#   show_ui: false

# aruco:
#   cmd: roslaunch concert_marker_detection arucoDetect.launch fiducial_len:=0.095
#   machine: concert@10.24.10.101

# control: 
#   cmd: echo run control
#   persistent: false
#   depends:
#     - bringup_control
#     - bringup_vision
#     - odometry
#   show_ui: false

